In [19]:
# Session on Fri 12.12.2025

# Email from WLP about this week's session said the following-
# "This week is the final session. We’ll be looking at writing our own functions. 
# Again, like last week, as it’s a harder session, we’ll probably only spend around an hour or so introducing the topic."

# WLP said the following about today's session
# It's an important but not hard session, and we'll be using stuff we've done in a previous session
# Things will start to now become alive in Python!
# So far we've done some things in PBI, but not others like for loops
# Let's start some things not relevant to children's services, but eventually we will
# We won't be able to look at functions fully (not a deep dive)

# .ipynb - this is a Python file

# Last week we did (for) loops and (if/elif/else) conditionals 
# Indentations are part of loop otherwise not

In [20]:
# A function allows you to reuse a piece of code parsing whatever parameters to it so you can do it multiple times or do it multiple times with different parameters
# Use function if you know you need to do it again and again
# Let's write a function - fn is function name
# Indentations are part of function (4 spaces or 1 tab is indentation)
def fn():
    print('Hello, world!')

# You have to do next line for it to work - 'call' the function
fn()

Hello, world!

In [21]:
# Add a variable in the parentheses
def fn(phrase):
    print(phrase)

fn(phrase='Hello, world!')
fn('I am Will!')

Hello, world!
I am Will!

In [22]:
def fxy(x, y):
    print(f'The sum of {x} and {y} is {x + y}')

fxy(x=7, y=13)
fxy(y=22, x=12)
# x=9 and y=12 below
fxy(9, 12)

The sum of 7 and 13 is 20
The sum of 12 and 22 is 34
The sum of 9 and 12 is 21

In [23]:
def fxy(x=90, y=10):
    print(f'The sum of {x} and {y} is {x + y}')

fxy(x=7, y=13)
fxy(y=22, x=12)
# x=9 and y=12 below
fxy(9, 12)
# Below reverts to default (x=90 and y=10)
fxy()
# x is default again
fxy(y=9)

The sum of 7 and 13 is 20
The sum of 12 and 22 is 34
The sum of 9 and 12 is 21
The sum of 90 and 10 is 100
The sum of 90 and 9 is 99

In [ ]:
# Group exercise
# Now it's your go. Write a function, with an appropriate name
# that divides one number by the other. Bonus points if you can make the function # always divide the largest of the two numbers by the smallest.
# For the latter  use conditional
# Get the function to print the answer

# My attempt below
# def fdiv(x, y):
#     print(f'Dividing larger number by smaller number is {max(x,y) / min(x,y)}')

# fxy(x=80, y=10)
# Result was 'The sum of 80 and 10 is 90'!

# WLP's way to do it - simple not doing extension bit about dividing bigger number by smaller one
def divide_nums(x, y):
    print(x / y)

# Full version
def divide_nums(x, y):
    if x > y:
        print(x / y)
    else:
        print(y / x)

divide_nums(10, 11)
divide_nums(100, 20)

1.1
5.0

In [29]:
# answer is my new variable 
answer = divide_nums(10, 100)
answer

10.0

In [31]:
print(answer)
# Answer is 'None' not 10!

None

In [ ]:
print(type(answer))
# It's a NoneType

<class 'NoneType'>

In [37]:
# Let's get stuff out of a function now!#
def divide_nums_return(x, y):
    if x > y:
        z = x / y
    else:
        z = y / x
    return z

ans = divide_nums_return(10, 100)
# No result for above
print(ans)
# Now we get 10.0 as result!

10.0

In [39]:
special_number = 10 # variables defined outside of functions can be used everywhere (global scope)

def divide_nums_return(x, y):
    # Variables defined inside functions can only be used inside functions (local scope)
    if x > y:
        z = x / y
    else:
        z = y / x
    print(special_number)
    return z

ans = divide_nums_return(10, 100)
print(ans)

10
10.0

In [ ]:
def sum_prod(i, j):
    sum = i + j
    prod = i * j

    return sum, prod

answer = sum_prod(44, 97)
print(answer)
print(type(answer))
# Type is a tuple
# Functions returning more than 1 variable can retturn them as a single tuple 

# Functions returning more than 1 variable can retturn them as multiple variables
ans_sum, ans_prod = sum_prod(34, 98)
print(ans_sum)
print(ans_prod)
print(type(ans_sum))

(141, 4268)
<class 'tuple'>
132
3332
<class 'int'>

In [ ]:
# WLP's version of above

def sum_prod(i, j):
    sum = i + j
    prod = i * j

    return sum, prod

# fucntions returning more than one variable can return them as a 
# single tuple
answer = sum_prod(44, 97)
print(answer)
print(type(answer))


# or as multiple variables
ans_sum, ans_prod = sum_prod(34, 98)
print(ans_sum)
print(ans_prod)
print(type(ans_sum))

(141, 4268)
<class 'tuple'>
132
3332
<class 'int'>

In [ ]:
# Group exercise
# write a function that returns x / y and x - y, 
# always dividing the biggest by the smallest number 
# and always taking the smallest from the biggest

# My version below
# def rkm(a, b):
#     if a > b:
#         divide = a / b
#         subtract = a - b
#     else if b > a:
#         divide = b / a
#         subtract = b - a
#     print(divide, subtract)
#     return divide, subtract
# I didn't check the above btw

# WLP's version
def sums(j, k):
    if j > k:
        division_answer = j / k
        sub_answer = j - k
    else:
        division_answer = k / j
        sub_answer = k /j
    return division_answer, sub_answer

In [49]:
# Another shorter way -  but is it beneficial being shorter?
def sums(j, k):
    if j > k:
        return j / k, j - k
    else:
        return k / j, k - j

In [51]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildCharacteristics.csv')

df

     Unnamed: 0        LAchildID Ethnicity
0             0  RND000215205141      WIRT
1             1  RND000824303014      WROM
2             2  RND000750143123      AOTH
3             3  RND000909164501      MWBC
4             4  RND000382171815      APKN
..          ...              ...       ...
327         327  RND000112711501      WOTH
328         328  RND000513120794      WROM
329         329  RND000541643134      BCRB
330         330  RND000404939452      AIND
331         331  RND000589802835      WBRI

[332 rows x 3 columns]

In [ ]:
# Let's categorise by ethnic group (white or not white)

# This isn't a good idea:
# for row in df:
#     the code for the category

# Loops aren't ideal to do first - try another method instead
# Use (row) apply function instead

# 'W' at start of 'Ethnicity' column will be counted as White by us
# Let's write a conditional
def ethnic_check(ethnicity):
    # Square brackets to make a string (session 1)
    if ethnicity[0] == "W":
        return 'White'
    else:
        return 'Not White'

print(ethnic_check('WIRT'))
print(ethnic_check('MWBC'))

White
Not White

In [ ]:
def ethnic_check(ethnicity):
    # Square brackets to make a string (session 1)
    if ethnicity[0] == "W":
        return 'White'
    else:
        return 'Not White'

# .apply method passes value of each row into the function you've just made (ethnic_check)
df['Ethnic subgroup'] = df['Ethnicity'].apply(ethnic_check)

df[['Ethnicity', 'Ethnic subgroup']]

# For loop would have been slow so .apply method is actually really powerful!

    Ethnicity Ethnic subgroup
0        WIRT           White
1        WROM           White
2        AOTH       Not White
3        MWBC       Not White
4        APKN       Not White
..        ...             ...
327      WOTH           White
328      WROM           White
329      BCRB       Not White
330      AIND       Not White
331      WBRI           White

[332 rows x 2 columns]

In [ ]:
# Group exercise
# 'https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv'
# Write a function that calculates ages based on the data, and returns a new column in age range buckets
# 0-5, 6-11, 12-17, 18+

# import data
# write functions
# using conditionals
# change to date
# calculation on df columns
# making new column

# My method below
# import pandas as pd
# dfr = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv')
# dfr
# print(dfr['PersonBirthDate'].dtype)
# It's an object so need to convert to date
# Need to check below
# dfr['PersonBirthDate'] = pd.to_datetime(dfr['PersonBirthDate'])
# print(dfr['PersonBirthDate'].dtype)



# WLP's method below
df = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv')

def age_buckets(row):
    bday = pd.to_datetime(row, format="%Y-%m-%d")
    today = pd.to_datetime('today')

# Below is a long method
# Unit is days
    # age = (today - bday) / pd.Timedelta(365.25, 'D')

    # if age < 6:
        # return '0-5 years'
    # And so forth

    # Here's a snazzier way to do it!
    if bday + pd.DateOffset(years=6) > today:
        return '0-5 years'
    elif bday + pd.DateOffset(years=12) > today:
        return '6-11 years'
    elif bday + pf.DateOffset(years=18) > today:
        return '12 - 17 years'
    else:
        return '18+ years'

df['Age Buckets'] = df['PersonBirthDate'].apply(age_buckets)

df[['PersonBirthDate', 'Age Buckets']]

# Error happening in code I copied froom WLP's screen above

NameError: name 'pf' is not defined

In [62]:
# This is correct version but it's from WLP's notes for the session as his mouse wasn't working

df = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv')

def age_buckets(row):
    bday = pd.to_datetime(row, format="%Y-%m-%d")
    today = pd.to_datetime('today')

    # age = (today - bday)/pd.Timedelta(365.25, 'D')

    if bday + pd.DateOffset(years=6) > today:
        return '0-5 years'
    elif bday + pd.DateOffset(years=12) > today:
        return '6-11 years'
    elif bday + pd.DateOffset(years=18) > today:
        return '12-17 years'
    else:
        return '18+'
        
df['Age Bucket'] = df['PersonBirthDate'].apply(age_buckets)

df[['PersonBirthDate', 'Age Bucket']]

    PersonBirthDate   Age Bucket
0        2019-12-06   6-11 years
1        2011-04-27  12-17 years
2        2017-06-06   6-11 years
3        2014-10-03   6-11 years
4        2019-09-25   6-11 years
..              ...          ...
327      2010-07-07  12-17 years
328      2018-08-14   6-11 years
329      2021-12-09    0-5 years
330      2013-07-23  12-17 years
331      2021-10-25    0-5 years

[332 rows x 2 columns]

In [ ]:
# This was functions
# Hopefully everyone has learnt Python a little bit!
# Next session will be run in middle of next year
# Short courses he's planning - querying Sequel with Python, making simple web apps, into to data pipelines (data pre-processing in Python) etc
# Are you interested in certain things? Tell WLP!
# WLP used to do machine learning but he stopped as attendance was low - he could do machine bit but stats was hard (and most useful) and he didn't feel confident to teach that bit