In [4]:
# Session on Fri 21.11.2025

# First we will finishing off looking at simple logical selections for Pandas

# This session will look at stuff WLP does in his work regularly (CIN and 903 validation tools) to learn Pandas (validation e.g. DOBs need to make sense), plus make use of inequalities stuff looked at at the end of last session

# Next session will look at plotting, then Python programming type things (not related to data analysis or data science but will speed you up automating things)

In [5]:
# Session 4 being finished off first:

# Click 'Run All' to run all cells from last week (making sure you remove the inequalities bit we added at the end of the session)

# The following is an alternative which will summarise what we did last time

import pandas as pd

# dictionary of lists
child_info = pd.DataFrame({'ChildId':['id1', 'id2', 'id3', 'id4', 'id5'],
                           'Age at first contact':[6, 12, 11, 1, 19],
                           'SEX':['M', 'm', 'F', '', 'F'],
                           'Birthday':['01/01/2002', '02/02/2003', '01/01/2000', '03/03/2023', '06/01/2012'],
                           'CP Plan?':['Y', 'n', 'N', 'No', 'yES'],})

# list of dictionaries
nhs_numbers = pd.DataFrame([{'ChildId':'id1',
                             'NHS Number':'303'},
                             {'ChildId':'id2',
                              'NHS Number':'3u5029'},
                            {'ChildId':'id3',
                            'NHS Number': 'gqw3',},
                            {'ChildId':'id4',
                            'NHS Number': 'avsgvb',},
                            {'ChildId':'id5',
                            'NHS Number': 'varwvw',},])

nhs_numbers

  ChildId NHS Number
0     id1        303
1     id2     3u5029
2     id3       gqw3
3     id4     avsgvb
4     id5     varwvw

In [6]:
# To look at under 5s
# Write criteria in square brackets (square brackets mean we're making a selection or doing a slice) or have it elsewhere and put in square brackets later
# under_5_df = child_info[]

# import pandas as pd

# Method 1
# cond means condition
under_5_cond = child_info['Age at first contact'] < 5
under_5_cond
# I'm getting errors because Age column isn't being found (probably because WLP didn't give the whole code just end bit of it) but he was getting a list of trues and falses

under_5_df = child_info[under_5_cond]
under_5_df
# This showed dataframe on WLP's screen but I was getting an error again due to 'Age' column causing chaos

ages_5_and_under_cond = child_info['Age at first contact'] <= 5

# The following 2 will give the same if it works lol
ages_5_and_under = child_info[ages_5_and_under_cond]
ages_5_and_under

# ~ means negation or 'not'

over_5_df = child_info[~ages_5_and_under_cond]
over_5_df
# This gives 6 and over

# Method 2
# ... 



# Code WLP gave:
# under_5_cond = child_info['Age'] < 5

# under_5_df = child_info[under_5_cond]

# ages_5_and_under_cond = child_info['Age'] <= 5

# ages_5_and_under = child_info[ages_5_and_under_cond]

# over_5_df = child_info[~ages_5_and_under_cond]

# over_5_df

  ChildId  Age at first contact SEX    Birthday CP Plan?
0     id1                     6   M  01/01/2002        Y
1     id2                    12   m  02/02/2003        n
2     id3                    11   F  01/01/2000        N
4     id5                    19   F  06/01/2012      yES

In [7]:
# | or, & and

# We want to see over 5 and under 20 (6 or over and 19 or under)
# This makes sense mathematically but has to be done separately in Python: 20>= child_info['Age'] >= 5
over_5 = child_info['Age at first contact'] >=5
under_20 = child_info['Age at first contact'] < 20
print(over_5)
print(under_20)
# You will get a list of trues and falses
condition = over_5 & under_20
print(condition)
# It's telling us where both are true now
between_5_and_20 = child_info[condition]
print(between_5_and_20)

0     True
1     True
2     True
3    False
4     True
Name: Age at first contact, dtype: bool
0    True
1    True
2    True
3    True
4    True
Name: Age at first contact, dtype: bool
0     True
1     True
2     True
3    False
4     True
Name: Age at first contact, dtype: bool
  ChildId  Age at first contact SEX    Birthday CP Plan?
0     id1                     6   M  01/01/2002        Y
1     id2                    12   m  02/02/2003        n
2     id3                    11   F  01/01/2000        N
4     id5                    19   F  06/01/2012      yES

In [8]:
# First condition is made up of 2 conditions which will end up being true or false, and condition 3 can be either true or false
# outcome = df[condition_1 & condition_2 | condition_3]

In [9]:
# Session 5 starts here (at 13.32hrs)

# It's installed but pandas needs to be imported in
import pandas as pd

filepath = "https://github.com/data-to-insight/ERN-sessions/raw/main/data/903_xlsx_errors.xlsx"
# Simple way - dfs = pd.read_excel(filepath)
# Let's read in every table in excel by doing the following (None must have capital N at start)
dfs = pd.read_excel(filepath, sheet_name=None)
# Put in 'header' just for header tab, but can include multiple tabs too
# dfs
# This dataframe is 3 years old so will look different nowadays lol

# dfs.keys()

# You will see top 5 rows here
# Good idea to have Excel open on another screen :)
dfs['header'].head()

    CHILD  SEX         DOB ETHNIC            UPN  MOTHER MC_DOB
0  566910    2  27/03/2008   WROM  D051910639385     NaN    NaN
1  384923    2  09/09/2011   REFU  L034811502612     NaN    NaN
2  709901    1  14/02/2013   ABAN  Y021751958510     NaN    NaN
3  550084    2  04/05/2008   AOTH  R095578985099     NaN    NaN
4  710229    2  15/04/2002   REFU  Z095096287583     NaN    NaN

In [10]:
# Rule 102 in 903 validator says date of birth is not a valid date

# Dates have to be formatted as d/m/y for 903 return
# to_datetime() (i.e. to_datetime function) - you can format argument e.g. "%d/%m/%Y" (2 digit day and month and 4 digit year)
# errors = "coerce" <-- This will return an NA for every row where date wasn't formatted correctly

header = dfs['header']

# Let's add a new column called DOB_dt (let's not overwrite original DOB column - let's do nondestructive work!)
header['DOB_dt'] = pd.to_datetime(header['DOB'], format="%d/%m/%Y", errors='coerce')

invalid_dobs = header['DOB_dt'].isna()
# True if there's an NA 

error_rows = header[invalid_dobs]
error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [11]:
# Group exercise
# Rule 115 - Date of LA's decision that a child should be placed for adoption is not a valid date
# table = placed_for_adoption, col = DATE_PLACED

# I think we're calling the placed_for_adoption table p4a for short (in my attempt I was missing this bit)
p4a = dfs['placed_for_adoption']
# I think below means let's add a new DATE_PLACED_dt column which is based on original DATE_PLACED column giving date in dd/mm/yyyy format with errors given as NA
p4a['DATE_PLACED_dt'] = pd.to_datetime(p4a['DATE_PLACED'], format="%d/%m/%Y", errors='coerce')
# Now let's try to see the NAs in the new DATE_PLACED_dt column
# You can do it in 1 line as below or in 2 lines (like in example WLP did above?)
invalid_dp = p4a[p4a['DATE_PLACED_dt'].isna()]
invalid_dp

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT

In [13]:
# Let's look at something new now!

# Tip for me - If I close my codespace and reopen it I have to Run All! 

# Rule 103 - The ethnicity code is either not valid ot has not been entered
# header, ETHNIC - emmpty or not a valid code

# Valid ethnicity codes are as follows: 
# 103 - The ethnicity code is either not valid or has not been entered.
# header, ETHNIC - empty, or not a valid code

ethnicity_codes = [
        "WBRI",
        "WIRI",
        "WOTH",
        "WIRT",
        "WROM",
        "MWBC",
        "MWBA",
        "MWAS",
        "MOTH",
        "AIND",
        "APKN",
        "ABAN",
        "AOTH",
        "BCRB",
        "BAFR",
        "BOTH",
        "CHNE",
        "OOTH",
        "REFU",
        "NOBT",
    ]

# .isin()

error_rows = header[~header['ETHNIC'].isin(ethnicity_codes)]

error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [20]:
# Group exercise 
# Rule 114 - Data entry to record the status of former carer(s) of an adopted child is invalid.
# table - ad1
# FOSTER_CARE
# valid codes 0, 1

ad1 = dfs['ad1']
# Everything in FOSTER_CARE column is a string
ad1['FOSTER_CARE'] = ad1['FOSTER_CARE'].astype('str')
# .isin looks at strings
error_rows = ad1[~ad1['FOSTER_CARE'].isin(["0","1"])]
error_rows

,CHILD,DOB,DATE_INT,DATE_MATCH,FOSTER_CARE,NB_ADOPTR,SEX_ADOPTR,LS_ADOPTR
29,bad_entry,datedate,notdate,datenot,777,Q,Will,let's go

In [ ]:
# Next example is Rule 184 - Date of decision that a child should be placed for adoption is before the child was born

p4a
# p4a has DOB in it but let's pretend is doesn't lol

# We care abour DOB which we'll pretend is only in header and DATE_PLACED which is in p4a
# Find rows where DATE_PLACED is before DOB i.e. DATE_PLACED < DOB (i.e. is before)
# We need DOB and DATE_PLACED (well header has DATE_PLACED_dt already as we put it in lol) as datetime objects, and merge header and p4a

# p4a is our left hand table, header will be right hand table
# Let's merge on CHILD column
# Different merges (e.g. left) can be found doing a Google search
merged_df = p4a.merge(header, on='CHILD', how='left')
merged_df

# We just wanted DOB_dt not ethnicity column etc 

# When making a selection of more than 1 column, pass a list of columns
merged_df = p4a.merge(header[['CHILD', 'DOB_dt']], on='CHILD', how='left')
merged_df

error_rows = merged_df[merged_df['DOB_dt'] > merged_df['DATE_PLACED_dt']]
error_rows
# Nothing comes out as there were no errors

Empty DataFrame
Columns: [CHILD, DOB, DATE_PLACED, DATE_PLACED_CEASED, REASON_PLACED_CEASED, DATE_PLACED_dt, DOB_dt]
Index: []

In [36]:
# Group exercise
# Rule 102 - First episode starts before child was born
# tables are header and episodes
# DOB from header and DECOM from episodes

# I added this in so I got a reminder of what header table looks like - dfs['header'].head()
# I added this in so I got a reminder of what episodes table looks like - dfs['episodes'].head()

# WLP's code below:
# Let's read in episodes table?
episodes = dfs['episodes']
# Let's make a new DECOM_dt column which is based on DECOM column - what is dayfirst?
episodes['DECOM_dt'] = pd.to_datetime(episodes['DECOM'], dayfirst=True)
df = episodes.merge(header[['CHILD', 'DOB_dt']], how='left', on='CHILD')
error_rows = df[df['DECOM_dt'] < df['DOB_dt']]
error_rows

# My attempt
# merged_df = header.merge(episodes[['CHILD', 'DOB_dt']], on='CHILD', how='left')
# error_rows = merged_df[merged_df['DOB_dt'] > merged_df['DECOM']]
# error_rows

Empty DataFrame
Columns: [CHILD, DECOM, RNE, LS, CIN, PLACE, PLACE_PROVIDER, DEC, REC, REASON_PLACE_CHANGE, HOME_POST, PL_POST, URN, DECOM_dt, DOB_dt]
Index: []

In [35]:
# sort_values() method
# drop_duplicates() method


# Give columns you want to sort by on RHS
# CHILD numbers will get bigger and DECOM date will go from earlier to later
epi_ordered = episodes.sort_values(['CHILD', 'DECOM_dt'], ascending=True)

episodes

first_epi = epi_ordered.drop_duplicates('CHILD', keep='first')

first_epi

,CHILD,DECOM,RNE,LS,CIN,PLACE,PLACE_PROVIDER,DEC,REC,REASON_PLACE_CHANGE,HOME_POST,PL_POST,URN,DECOM_dt
4801,32,12/02/2017,T,J1,N3,K2,PR1,15/04/2017,E3,NaN,ED8 1OX,WI5 9CC,7876040,2017-02-12
4041,982,27/11/2016,P,E1,N7,A5,PR3,07/10/2017,X1,LAREQ,EP10 1XZ,WI5 8XU,6162294,2016-11-27
437,1243,02/01/2017,L,V4,N5,Z1,PR0,18/05/2017,E9,NaN,EC5 5MZ,WC30 9OS,7270736,2017-01-02
1794,1407,28/11/2015,L,L2,N3,P2,PR1,29/04/2017,X1,ALLEG,EG16 2ZL,WU19 1JS,6492318,2015-11-28
3848,2431,20/02/2016,S,V2,N3,P2,PR5,18/11/2017,X1,APPRR,EK12 3JI,WV1 1FJ,5227516,2016-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,997201,18/05/2016,P,L3,N4,T3,PR3,07/06/2017,X1,CUSTOD,EL12 3BA,WV22 6GC,3780837,2016-05-18
2766,997445,20/06/2016,P,J1,N2,U3,PR3,24/09/2017,E48,NaN,EP2 2VO,WE6 1FZ,3786993,2016-06-20
154,998192,27/11/2015,P,C2,N2,P1,PR5,08/07/2017,X1,ALLEG,EJ11 4FS,WT21 5RE,6722585,2015-11-27
156,998777,11/10/2015,P,C2,N2,U1,PR2,17/03/2018,X1,CLOSE,ER24 5VS,WJ7 5PQ,1112628,2015-10-11
323,999397,17/02/2017,L,L1,N7,P2,PR1,29/08/2017,X1,NaN,EC5 2KK,WV19 3SY,3534004,2017-02-17

In [ ]:
# Next session will be doing plotting using matlib(?)

# In advanced Python sessions WLP runs he will show how dashboards integrate into your work 
# Someone put this in the chat - about using Tableu (drag and drop) for dashboards which integrate with Jupyter Notebooks - https://pypi.org/project/pygwalker/